name: Test

on:
  pull_request:
    branches: ["master", "dev"]
  push:
    branches: ["master"]

jobs:
  sveltecheck:
    name: Ê¦ Svelte check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - name: Install latest packages
        run: bun install --verbose
      - name: Check with svelte-check
        run: bun run check
